### ISSUE TITLE
squidguard log not showing in kibana

### ISSUE THREAD

**Issue by cusco** [muenchhausen/docker-squidguard-elk#5]
Hello,

the proxy seems to be working but no data gets logged. Kibana finds nothing to index.

I'm not proficient on elk, logstash and kibana but here is a exert from the docker log on elk container, that may be useful?

Also, how does logstash works, does it read squid log and sends it to elk socket, or does it listens to a port, and squid talks to it? I ask because I see no ports open on the filebeat container

==> /var/log/logstash/logstash-plain.log <==

[2018-12-03T11:40:07,312][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"fb_apache", :directory=>"/opt/logstash/modules/fb_apache/configuration"}

[2018-12-03T11:40:07,327][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"netflow", :directory=>"/opt/logstash/modules/netflow/configuration"}

[2018-12-03T11:40:07,394][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.queue", :path=>"/opt/logstash/data/queue"}

[2018-12-03T11:40:07,397][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.dead_letter_queue", :path=>"/opt/logstash/data/dead_letter_queue"}

[2018-12-03T11:40:07,716][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified

[2018-12-03T11:40:07,744][INFO ][logstash.agent           ] No persistent UUID file found. Generating new UUID {:uuid=>"d4af3e84-d104-47ab-8d37-40b1d9597bea", :path=>"/opt/logstash/data/uuid"}

[2018-12-03T11:40:08,423][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"6.1.1"}

[2018-12-03T11:40:08,945][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}

[2018-12-03T11:40:09,901][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::ConfigurationError", :message=>"Expected one of #, if, \", ', } at line 13, column 6 (byte 515) after filter {\n\tif [type] == \"squid\" {\n\t    grok {\n\t        match => {\"message\" => \"%{NUMBER:timestamp}\\s+%{NUMBER:request_msec:float} %{IPORHOST:src_ip} %{WORD:request_status}/%{NUMBER:response_status:int} %{NUMBER:response_size:int} %{WORD:http_method} (%{URIPROTO:http_proto}://)?%{IPORHOST:dst_host}(?::%{POSINT:port})?(?:%{NOTSPACE:uri_param})? %{USERNAME:user} %{WORD}/(%{IPORHOST:dst_ip}|-) %{GREEDYDATA:content_type}\"}\n\t        named_captures_only => true      \n\t    }\n\t    ", :backtrace=>["/opt/logstash/logstash-core/lib/logstash/compiler.rb:42:in `compile_imperative'", "/opt/logstash/logstash-core/lib/logstash/compiler.rb:50:in `compile_graph'", "/opt/logstash/logstash-core/lib/logstash/compiler.rb:12:in `block in compile_sources'", "org/jruby/RubyArray.java:2486:in `map'", "/opt/logstash/logstash-core/lib/logstash/compiler.rb:11:in `compile_sources'", "/opt/logstash/logstash-core/lib/logstash/pipeline.rb:51:in `initialize'", "/opt/logstash/logstash-core/lib/logstash/pipeline.rb:171:in `initialize'", "/opt/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:40:in `execute'", "/opt/logstash/logstash-core/lib/logstash/agent.rb:335:in `block in converge_state'", "/opt/logstash/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/opt/logstash/logstash-core/lib/logstash/agent.rb:332:in `block in converge_state'", "org/jruby/RubyArray.java:1734:in `each'", "/opt/logstash/logstash-core/lib/logstash/agent.rb:319:in `converge_state'", "/opt/logstash/logstash-core/lib/logstash/agent.rb:166:in `block in converge_state_and_update'", "/opt/logstash/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/opt/logstash/logstash-core/lib/logstash/agent.rb:164:in `converge_state_and_update'", "/opt/logstash/logstash-core/lib/logstash/agent.rb:90:in `execute'", "/opt/logstash/logstash-core/lib/logstash/runner.rb:343:in `block in execute'", "/opt/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:24:in `block in initialize'"]}

**Comment by cusco** [comment]
why was it closed?

**Comment by muenchhausen** [comment]
In your log excerpt you find: "LogStash::ConfigurationError", :message=>"Expected one of #, if, ", ', } at line 13"

Also in my environment it wasn't working any longer because of a config error in elk/5001-squid-filter.conf.

After changing that - elk works fine. 

Please let me know if this fixes your problem.
